name: NASA Project CI
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: action/checkout@v2
      - name: Setup Node.js 20
        uses: action/setup-node@v2
        with:
          node-version: '20'
      - name: Install Dependencies
        run: npm-install
      - name: Build Front End
        run: npm run build --prefix-client
  # deploy:
  #   needs: build